var searchData=
[
  ['build_520',['build',['../d1/d52/namespacedolfinx_1_1graph_1_1build.html',1,'dolfinx::graph']]],
  ['cells_521',['cells',['../df/dcf/namespacedolfinx_1_1io_1_1cells.html',1,'dolfinx::io']]],
  ['common_522',['common',['../d7/de1/namespacedolfinx_1_1common.html',1,'dolfinx']]],
  ['fem_523',['fem',['../d8/dbf/namespacedolfinx_1_1fem.html',1,'dolfinx']]],
  ['geometry_524',['geometry',['../de/d27/namespacedolfinx_1_1geometry.html',1,'dolfinx']]],
  ['graph_525',['graph',['../d9/d69/namespacedolfinx_1_1graph.html',1,'dolfinx']]],
  ['io_526',['io',['../d6/d7a/namespacedolfinx_1_1io.html',1,'dolfinx']]],
  ['kahip_527',['kahip',['../d9/d24/namespacedolfinx_1_1graph_1_1kahip.html',1,'dolfinx::graph']]],
  ['la_528',['la',['../d6/dfa/namespacedolfinx_1_1la.html',1,'dolfinx']]],
  ['mesh_529',['mesh',['../dd/d7d/namespacedolfinx_1_1mesh.html',1,'dolfinx']]],
  ['mpi_530',['MPI',['../da/dfe/namespacedolfinx_1_1MPI.html',1,'dolfinx']]],
  ['nls_531',['nls',['../df/d80/namespacedolfinx_1_1nls.html',1,'dolfinx']]],
  ['options_532',['options',['../dd/d01/namespacedolfinx_1_1la_1_1petsc_1_1options.html',1,'dolfinx::la::petsc']]],
  ['petsc_533',['petsc',['../d4/d44/namespacedolfinx_1_1fem_1_1petsc.html',1,'dolfinx::fem']]],
  ['plaza_534',['plaza',['../df/dfe/namespacedolfinx_1_1refinement_1_1plaza.html',1,'dolfinx::refinement']]],
  ['refinement_535',['refinement',['../d9/dd6/namespacedolfinx_1_1refinement.html',1,'dolfinx']]],
  ['sparsitybuild_536',['sparsitybuild',['../db/dcc/namespacedolfinx_1_1fem_1_1sparsitybuild.html',1,'dolfinx::fem']]],
  ['subsystem_537',['subsystem',['../d2/dcc/namespacedolfinx_1_1common_1_1subsystem.html',1,'dolfinx::common']]],
  ['xdmf_5ffunction_538',['xdmf_function',['../df/dbd/namespacedolfinx_1_1io_1_1xdmf__function.html',1,'dolfinx::io']]],
  ['xdmf_5fmesh_539',['xdmf_mesh',['../d0/dfe/namespacedolfinx_1_1io_1_1xdmf__mesh.html',1,'dolfinx::io']]],
  ['xdmf_5fread_540',['xdmf_read',['../d8/de2/namespacedolfinx_1_1io_1_1xdmf__read.html',1,'dolfinx::io']]]
];
