var searchData=
[
  ['build_494',['build',['../d1/d52/namespacedolfinx_1_1graph_1_1build.html',1,'dolfinx::graph']]],
  ['cells_495',['cells',['../df/dcf/namespacedolfinx_1_1io_1_1cells.html',1,'dolfinx::io']]],
  ['common_496',['common',['../d7/de1/namespacedolfinx_1_1common.html',1,'dolfinx']]],
  ['fem_497',['fem',['../d8/dbf/namespacedolfinx_1_1fem.html',1,'dolfinx']]],
  ['geometry_498',['geometry',['../de/d27/namespacedolfinx_1_1geometry.html',1,'dolfinx']]],
  ['graph_499',['graph',['../d9/d69/namespacedolfinx_1_1graph.html',1,'dolfinx']]],
  ['io_500',['io',['../d6/d7a/namespacedolfinx_1_1io.html',1,'dolfinx']]],
  ['kahip_501',['kahip',['../d9/d24/namespacedolfinx_1_1graph_1_1kahip.html',1,'dolfinx::graph']]],
  ['la_502',['la',['../d6/dfa/namespacedolfinx_1_1la.html',1,'dolfinx']]],
  ['mesh_503',['mesh',['../dd/d7d/namespacedolfinx_1_1mesh.html',1,'dolfinx']]],
  ['mpi_504',['MPI',['../da/dfe/namespacedolfinx_1_1MPI.html',1,'dolfinx']]],
  ['nls_505',['nls',['../df/d80/namespacedolfinx_1_1nls.html',1,'dolfinx']]],
  ['options_506',['options',['../dd/d01/namespacedolfinx_1_1la_1_1petsc_1_1options.html',1,'dolfinx::la::petsc']]],
  ['petsc_507',['petsc',['../d4/d44/namespacedolfinx_1_1fem_1_1petsc.html',1,'dolfinx::fem']]],
  ['plaza_508',['plaza',['../df/dfe/namespacedolfinx_1_1refinement_1_1plaza.html',1,'dolfinx::refinement']]],
  ['refinement_509',['refinement',['../d9/dd6/namespacedolfinx_1_1refinement.html',1,'dolfinx']]],
  ['sparsitybuild_510',['sparsitybuild',['../db/dcc/namespacedolfinx_1_1fem_1_1sparsitybuild.html',1,'dolfinx::fem']]],
  ['subsystem_511',['subsystem',['../d2/dcc/namespacedolfinx_1_1common_1_1subsystem.html',1,'dolfinx::common']]],
  ['xdmf_5ffunction_512',['xdmf_function',['../df/dbd/namespacedolfinx_1_1io_1_1xdmf__function.html',1,'dolfinx::io']]],
  ['xdmf_5fmesh_513',['xdmf_mesh',['../d0/dfe/namespacedolfinx_1_1io_1_1xdmf__mesh.html',1,'dolfinx::io']]],
  ['xdmf_5fread_514',['xdmf_read',['../d8/de2/namespacedolfinx_1_1io_1_1xdmf__read.html',1,'dolfinx::io']]]
];
