var searchData=
[
  ['build_548',['build',['../d1/d52/namespacedolfinx_1_1graph_1_1build.html',1,'dolfinx::graph']]],
  ['cells_549',['cells',['../df/dcf/namespacedolfinx_1_1io_1_1cells.html',1,'dolfinx::io']]],
  ['common_550',['common',['../d7/de1/namespacedolfinx_1_1common.html',1,'dolfinx']]],
  ['fem_551',['fem',['../d8/dbf/namespacedolfinx_1_1fem.html',1,'dolfinx']]],
  ['geometry_552',['geometry',['../de/d27/namespacedolfinx_1_1geometry.html',1,'dolfinx']]],
  ['graph_553',['graph',['../d9/d69/namespacedolfinx_1_1graph.html',1,'dolfinx']]],
  ['io_554',['io',['../d6/d7a/namespacedolfinx_1_1io.html',1,'dolfinx']]],
  ['kahip_555',['kahip',['../d9/d24/namespacedolfinx_1_1graph_1_1kahip.html',1,'dolfinx::graph']]],
  ['la_556',['la',['../d6/dfa/namespacedolfinx_1_1la.html',1,'dolfinx']]],
  ['mesh_557',['mesh',['../dd/d7d/namespacedolfinx_1_1mesh.html',1,'dolfinx']]],
  ['mpi_558',['MPI',['../da/dfe/namespacedolfinx_1_1MPI.html',1,'dolfinx']]],
  ['nls_559',['nls',['../df/d80/namespacedolfinx_1_1nls.html',1,'dolfinx']]],
  ['options_560',['options',['../dd/d01/namespacedolfinx_1_1la_1_1petsc_1_1options.html',1,'dolfinx::la::petsc']]],
  ['petsc_561',['petsc',['../d4/d44/namespacedolfinx_1_1fem_1_1petsc.html',1,'dolfinx::fem']]],
  ['plaza_562',['plaza',['../df/dfe/namespacedolfinx_1_1refinement_1_1plaza.html',1,'dolfinx::refinement']]],
  ['refinement_563',['refinement',['../d9/dd6/namespacedolfinx_1_1refinement.html',1,'dolfinx']]],
  ['sparsitybuild_564',['sparsitybuild',['../db/dcc/namespacedolfinx_1_1fem_1_1sparsitybuild.html',1,'dolfinx::fem']]],
  ['xdmf_5ffunction_565',['xdmf_function',['../df/dbd/namespacedolfinx_1_1io_1_1xdmf__function.html',1,'dolfinx::io']]],
  ['xdmf_5fmesh_566',['xdmf_mesh',['../d0/dfe/namespacedolfinx_1_1io_1_1xdmf__mesh.html',1,'dolfinx::io']]],
  ['xdmf_5fread_567',['xdmf_read',['../d8/de2/namespacedolfinx_1_1io_1_1xdmf__read.html',1,'dolfinx::io']]]
];
