var searchData=
[
  ['dolfinx_0',['dolfinx',['../d2/dc7/namespacedolfinx.html',1,'']]],
  ['dolfinx_3a_3acommon_1',['common',['../d7/de1/namespacedolfinx_1_1common.html',1,'dolfinx']]],
  ['dolfinx_3a_3afem_2',['fem',['../d8/dbf/namespacedolfinx_1_1fem.html',1,'dolfinx']]],
  ['dolfinx_3a_3afem_3a_3apetsc_3',['petsc',['../d4/d44/namespacedolfinx_1_1fem_1_1petsc.html',1,'dolfinx::fem']]],
  ['dolfinx_3a_3afem_3a_3asparsitybuild_4',['sparsitybuild',['../db/dcc/namespacedolfinx_1_1fem_1_1sparsitybuild.html',1,'dolfinx::fem']]],
  ['dolfinx_3a_3ageometry_5',['geometry',['../de/d27/namespacedolfinx_1_1geometry.html',1,'dolfinx']]],
  ['dolfinx_3a_3agraph_6',['graph',['../d9/d69/namespacedolfinx_1_1graph.html',1,'dolfinx']]],
  ['dolfinx_3a_3agraph_3a_3abuild_7',['build',['../d1/d52/namespacedolfinx_1_1graph_1_1build.html',1,'dolfinx::graph']]],
  ['dolfinx_3a_3agraph_3a_3akahip_8',['kahip',['../d9/d24/namespacedolfinx_1_1graph_1_1kahip.html',1,'dolfinx::graph']]],
  ['dolfinx_3a_3aio_9',['io',['../d6/d7a/namespacedolfinx_1_1io.html',1,'dolfinx']]],
  ['dolfinx_3a_3aio_3a_3acells_10',['cells',['../df/dcf/namespacedolfinx_1_1io_1_1cells.html',1,'dolfinx::io']]],
  ['dolfinx_3a_3aio_3a_3axdmf_5ffunction_11',['xdmf_function',['../df/dbd/namespacedolfinx_1_1io_1_1xdmf__function.html',1,'dolfinx::io']]],
  ['dolfinx_3a_3aio_3a_3axdmf_5fmesh_12',['xdmf_mesh',['../d0/dfe/namespacedolfinx_1_1io_1_1xdmf__mesh.html',1,'dolfinx::io']]],
  ['dolfinx_3a_3ala_13',['la',['../d6/dfa/namespacedolfinx_1_1la.html',1,'dolfinx']]],
  ['dolfinx_3a_3ala_3a_3apetsc_14',['petsc',['../d6/d2f/namespacedolfinx_1_1la_1_1petsc.html',1,'dolfinx::la']]],
  ['dolfinx_3a_3ala_3a_3apetsc_3a_3aoptions_15',['options',['../dd/d01/namespacedolfinx_1_1la_1_1petsc_1_1options.html',1,'dolfinx::la::petsc']]],
  ['dolfinx_3a_3amesh_16',['mesh',['../dd/d7d/namespacedolfinx_1_1mesh.html',1,'dolfinx']]],
  ['dolfinx_3a_3ampi_17',['MPI',['../da/dfe/namespacedolfinx_1_1MPI.html',1,'dolfinx']]],
  ['dolfinx_3a_3anls_18',['nls',['../df/d80/namespacedolfinx_1_1nls.html',1,'dolfinx']]],
  ['dolfinx_3a_3arefinement_19',['refinement',['../d9/dd6/namespacedolfinx_1_1refinement.html',1,'dolfinx']]],
  ['dolfinx_3a_3arefinement_3a_3aplaza_20',['plaza',['../df/dfe/namespacedolfinx_1_1refinement_1_1plaza.html',1,'dolfinx::refinement']]]
];
