name: Push homepage
on:
  push:
    paths:
      - "README.md"
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate index.html using pandoc
        run: |
          sudo apt update
          sudo apt install pandoc -y
          pandoc -s README.md -c pandoc.css -o index.html
      - name: Commit html file
        run: |
          git config --global user.email "fenics@github.com"
          git config --global user.name "FEniCS GitHub Actions"
          git add index.html
          git commit --allow-empty -m "Update homepage"
          git push
