name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

name: Push homepage
on:
  push:
    paths:
      - 'README.md'
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate index.html using pandoc
        run: |
          sudo apt update
          sudo apt install pandoc -y
          pandoc -s README.md -c pandoc.css -o index.html
      - name: Commit html file
        run: |
          git config --global user.email "fenics@github.com"
          git config --global user.name "FEniCS GitHub Actions"
          git commit -am --allow-empty "Update homepage"
          git push
